import { Car } from '@/types/FilterSidebar';
import { ReviewProps } from '@/types/reviews';
import alexStan from '/src/public/images/alex_stan.png';
import skylarDias from '/src/public/images/skylar_dias.png';
import rFera from '/src/public/images/r_fera.png';
import andrew from '/src/public/images/andrew.png';
import pixabay from '/src/public/images/pixabay.png';
import { Cars } from '@/types/Recommendation';
// import allNewRush from '../app/images/recommendation/All New Rush.png';
import crv1 from '../app/images/recommendation/CR-V.png';
import crv2 from '../app/images/recommendation/CR-V2.png';
// import allNewTerios from '../app/images/recommendation/All New Terios.png';
import mgzxExcite from '../app/images/recommendation/MGZX Excite.png';
import mgzxExclusive from '../app/images/recommendation/MGZX Exclusive.png';
import newMgzs from '../app/images/recommendation/New MGZS.png';
import newMgzs2 from '../app/images/recommendation/New MGZS2.png';
import koenigsegg from '../assets/carKoenigsegg.png';
import nissangt from '../assets/carNissanGT-R.png';
import rollsRoyce from '../assets/carRolls-Royce.png';
import allNewRush from '../assets/allNewRush.png';
import crV from '../assets/cr-v.png';
import allNewTerios from '../assets/allNewTerios.png';
import mgZX from '../assets/mgZxExclusice.png';
import mgZs from '../assets/mgZxExcite.png';

export const dummyCars: Car[] = [
  { id: 1, name: 'Dogan', type: 'Sport', capacity: '10 people', price: 1 },
  { id: 2, name: 'Car 2', type: 'SUV', capacity: '2 Person', price: 75 },
  { id: 3, name: 'Sahin', type: 'Sport', capacity: '2 Person', price: 75 },
  { id: 4, name: 'Murat', type: 'Sport', capacity: '4 Person', price: 90 },
  { id: 5, name: 'Car 5', type: 'SUV', capacity: '4 Person', price: 90 },
  { id: 6, name: 'Car 6', type: 'SUV', capacity: '4 Person', price: 90 },
  { id: 7, name: 'Tempra', type: 'Sedan', capacity: '6 Person', price: 85 },
  { id: 8, name: 'Car 8', type: 'SUV', capacity: '8 or More', price: 60 },
  { id: 9, name: 'Car 9', type: 'SUV', capacity: '8 or More', price: 60 },
  {
    id: 10,
    name: 'Car 10',
    type: 'random type',
    capacity: '8 or More',
    price: 60,
  },
  {
    id: 13,
    name: 'Car 11',
    type: 'random type2',
    capacity: '10 or More',
    price: 60,
  },
  { id: 11, name: 'Car 12', type: 'Sport', capacity: '4 Person', price: 90 },
  {
    id: 1,
    name: 'Koenigsegg',
    type: 'Sport',
    capacity: '90L',
    users: '2 People',
    price: '$99.00',
    img: koenigsegg.src,
  },
  {
    id: 2,
    name: 'Nissan GT - R',
    type: 'Sport',
    capacity: '80L',
    users: '2 People',
    price: '$80.00',
    img: nissangt.src,
  },
  {
    id: 3,
    name: 'Rolls - Royce',
    type: 'Sedan',
    capacity: '70L',
    users: '4 People',
    price: '$96.00',
    img: rollsRoyce.src,
  },
  {
    id: 4,
    name: 'Nissan GT - R',
    type: 'Sport',
    capacity: '80L',
    users: '6 People',
    price: '$80.00',
    img: nissangt.src,
  },
  {
    id: 5,
    name: 'All New Rush',
    type: 'SUV',
    capacity: '70L',
    users: '6 People',
    price: '$72.00',
    img: allNewRush.src,
  },
  {
    id: 6,
    name: 'CR - V',
    type: 'SUV',
    capacity: '80L',
    users: '6 People',
    price: '$80.00',
    img: crV.src,
  },
  {
    id: 7,
    name: 'All New Terios',
    type: 'SUV',
    capacity: '90L',
    users: '6 People',
    price: '$74.00',
    img: allNewTerios.src,
  },
  {
    id: 8,
    name: 'CR - V',
    type: 'SUV',
    capacity: '80L',
    users: '6 People',
    price: '$80.00',
    img: crV.src,
  },
  {
    id: 9,
    name: 'MG ZX Exclusice',
    type: 'Hatchback',
    capacity: '70L',
    users: '4 People',
    price: '$76.00',
    img: mgZX.src,
  },
  {
    id: 10,
    name: 'New MG ZS',
    type: 'SUV',
    capacity: '80L',
    users: '6 People',
    price: '$80.00',
    img: mgZs.src,
  },
  {
    id: 11,
    name: 'MG ZX Excite',
    type: 'Hatchback',
    capacity: '90L',
    users: '4 People',
    price: '$74.00',
    img: mgZX.src,
  },
  {
    id: 12,
    name: 'New MG ZS',
    type: 'SUV',
    capacity: '80L',
    users: '6 People',
    price: '$80.00',
    img: mgZs.src,
  },
];

export const reviews: ReviewProps[] = [
  {
    id: 1,
    img: alexStan,
    name: 'Alex Stanton',
    title: 'CEO at Bukalapak',
    review:
      'We are very happy with the service from the MORENT App. Morent has a low price and also a large variety of cars with good and comfortable facilities. In addition, the service provided by the officers is also very friendly and very polite.',
    rating: 4,
    date: '2022-07-21',
  },
  {
    id: 2,
    img: skylarDias,
    name: 'Skylar Dias',
    title: 'CEO at Amazon',
    review:
      'We are greatly helped by the services of the MORENT Application. Morent has low prices and also a wide variety of cars with good and comfortable facilities. In addition, the service provided by the officers is also very friendly and very polite.',
    rating: 4,
    date: '2022-07-20',
  },
  {
    id: 3,
    img: rFera,
    name: 'Ray Fera',
    title: 'CEO at Somewhere',
    review:
      'We are greatly helped by the services of the MORENT Application. Morent has low prices and also a wide variety of cars with good and comfortable facilities. In addition, the service provided by the officers is also very friendly and very polite.',
    rating: 5,
    date: '2022-07-19',
  },
  {
    id: 4,
    img: andrew,
    name: 'Andrew Dias',
    title: 'CEO at Somewhere',
    review:
      'We are greatly helped by the services of the MORENT Application. Morent has low prices and also a wide variety of cars with good and comfortable facilities. In addition, the service provided by the officers is also very friendly and very polite.',
    rating: 3,
    date: '2022-07-22',
  },
  {
    id: 5,
    img: pixabay,
    name: 'Pixabay',
    title: 'CEO at pexels',
    review:
      'We are greatly helped by the services of the MORENT Application. Morent has low prices and also a wide variety of cars with good and comfortable facilities. In addition, the service provided by the officers is also very friendly and very polite.',
    rating: 5,
    date: '2022-07-22',
  },
];

export const dummyRecommendationCars: Cars[] = [
  {
    id: 1,
    name: 'All New Rush',
    img: allNewRush,
    type: 'SUV',
    capacity: '6 People',
    price: 72,
    gasoline: '70L',
    gear: 'Manual',
  },
  {
    id: 2,
    name: 'CR-V',
    img: crv1,
    type: 'SUV',
    capacity: '6 People',
    price: 80,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 3,
    name: 'All New Terios',
    img: allNewTerios,
    type: 'SUV',
    capacity: '6 People',
    price: 74,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 4,
    name: 'CR-V',
    img: crv2,
    type: 'SUV',
    capacity: '6 People',
    price: 80,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 5,
    name: 'MGZX Exclusive',
    img: mgzxExclusive,
    type: 'Hatchback',
    capacity: '4 People',
    price: 76,
    gasoline: '70L',
    gear: 'Manual',
  },
  {
    id: 6,
    name: 'New MGZS',
    img: newMgzs,
    type: 'SUV',
    capacity: '6 People',
    price: 80,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 7,
    name: 'MGZX Excite',
    img: mgzxExcite,
    type: 'Hatchback',
    capacity: '4 People',
    price: 74,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 8,
    name: 'New MGZS',
    img: newMgzs2,
    type: 'SUV',
    capacity: '6 People',
    price: 80,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 9,
    name: 'All New Rush 2',
    img: allNewRush,
    type: 'SUV',
    capacity: '6 People',
    price: 73,
    gasoline: '75L',
    gear: 'Automatic',
  },
  {
    id: 10,
    name: 'CR-V 2',
    img: crv1,
    type: 'SUV',
    capacity: '6 People',
    price: 81,
    gasoline: '85L',
    gear: 'Manual',
  },
  {
    id: 11,
    name: 'All New Terios 2',
    img: allNewTerios,
    type: 'SUV',
    capacity: '6 People',
    price: 75,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 12,
    name: 'MGZX Exclusive 2',
    img: mgzxExclusive,
    type: 'Hatchback',
    capacity: '4 People',
    price: 77,
    gasoline: '70L',
    gear: 'Manual',
  },
  {
    id: 13,
    name: 'New MGZS 2',
    img: newMgzs,
    type: 'SUV',
    capacity: '6 People',
    price: 81,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 14,
    name: 'MGZX Excite 2',
    img: mgzxExcite,
    type: 'Hatchback',
    capacity: '4 People',
    price: 75,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 15,
    name: 'New MGZS 3',
    img: newMgzs2,
    type: 'SUV',
    capacity: '6 People',
    price: 81,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 16,
    name: 'All New Rush 3',
    img: allNewRush,
    type: 'SUV',
    capacity: '6 People',
    price: 74,
    gasoline: '75L',
    gear: 'Automatic',
  },
  {
    id: 17,
    name: 'CR-V 3',
    img: crv1,
    type: 'SUV',
    capacity: '6 People',
    price: 82,
    gasoline: '85L',
    gear: 'Manual',
  },
  {
    id: 18,
    name: 'All New Terios 3',
    img: allNewTerios,
    type: 'SUV',
    capacity: '6 People',
    price: 76,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 19,
    name: 'MGZX Exclusive 3',
    img: mgzxExclusive,
    type: 'Hatchback',
    capacity: '4 People',
    price: 78,
    gasoline: '70L',
    gear: 'Manual',
  },
  {
    id: 20,
    name: 'New MGZS 4',
    img: newMgzs,
    type: 'SUV',
    capacity: '6 People',
    price: 82,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 21,
    name: 'MGZX Excite 3',
    img: mgzxExcite,
    type: 'Hatchback',
    capacity: '4 People',
    price: 76,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 22,
    name: 'New MGZS 5',
    img: newMgzs2,
    type: 'SUV',
    capacity: '6 People',
    price: 82,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 23,
    name: 'All New Rush 4',
    img: allNewRush,
    type: 'SUV',
    capacity: '6 People',
    price: 75,
    gasoline: '75L',
    gear: 'Automatic',
  },
  {
    id: 24,
    name: 'CR-V 4',
    img: crv1,
    type: 'SUV',
    capacity: '6 People',
    price: 83,
    gasoline: '85L',
    gear: 'Manual',
  },
  {
    id: 25,
    name: 'All New Terios 4',
    img: allNewTerios,
    type: 'SUV',
    capacity: '6 People',
    price: 77,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 26,
    name: 'MGZX Exclusive 4',
    img: mgzxExclusive,
    type: 'Hatchback',
    capacity: '4 People',
    price: 79,
    gasoline: '70L',
    gear: 'Manual',
  },
  {
    id: 27,
    name: 'New MGZS 6',
    img: newMgzs,
    type: 'SUV',
    capacity: '6 People',
    price: 83,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 28,
    name: 'MGZX Excite 4',
    img: mgzxExcite,
    type: 'Hatchback',
    capacity: '4 People',
    price: 77,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 29,
    name: 'New MGZS 7',
    img: newMgzs2,
    type: 'SUV',
    capacity: '6 People',
    price: 83,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 30,
    name: 'All New Rush 5',
    img: allNewRush,
    type: 'SUV',
    capacity: '6 People',
    price: 76,
    gasoline: '75L',
    gear: 'Automatic',
  },
  {
    id: 31,
    name: 'CR-V 5',
    img: crv1,
    type: 'SUV',
    capacity: '6 People',
    price: 84,
    gasoline: '85L',
    gear: 'Manual',
  },
  {
    id: 32,
    name: 'All New Terios 5',
    img: allNewTerios,
    type: 'SUV',
    capacity: '6 People',
    price: 78,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 33,
    name: 'MGZX Exclusive 5',
    img: mgzxExclusive,
    type: 'Hatchback',
    capacity: '4 People',
    price: 80,
    gasoline: '70L',
    gear: 'Manual',
  },
  {
    id: 34,
    name: 'New MGZS 8',
    img: newMgzs,
    type: 'SUV',
    capacity: '6 People',
    price: 84,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 35,
    name: 'MGZX Excite 5',
    img: mgzxExcite,
    type: 'Hatchback',
    capacity: '4 People',
    price: 78,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 36,
    name: 'New MGZS 9',
    img: newMgzs2,
    type: 'SUV',
    capacity: '6 People',
    price: 84,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 37,
    name: 'All New Rush 6',
    img: allNewRush,
    type: 'SUV',
    capacity: '6 People',
    price: 77,
    gasoline: '75L',
    gear: 'Automatic',
  },
  {
    id: 38,
    name: 'CR-V 6',
    img: crv1,
    type: 'SUV',
    capacity: '6 People',
    price: 85,
    gasoline: '85L',
    gear: 'Manual',
  },
  {
    id: 39,
    name: 'All New Terios 6',
    img: allNewTerios,
    type: 'SUV',
    capacity: '6 People',
    price: 79,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 40,
    name: 'MGZX Exclusive 6',
    img: mgzxExclusive,
    type: 'Hatchback',
    capacity: '4 People',
    price: 81,
    gasoline: '70L',
    gear: 'Manual',
  },
  {
    id: 41,
    name: 'New MGZS 10',
    img: newMgzs,
    type: 'SUV',
    capacity: '6 People',
    price: 85,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 42,
    name: 'MGZX Excite 6',
    img: mgzxExcite,
    type: 'Hatchback',
    capacity: '4 People',
    price: 79,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 43,
    name: 'New MGZS 11',
    img: newMgzs2,
    type: 'SUV',
    capacity: '6 People',
    price: 85,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 44,
    name: 'All New Rush 7',
    img: allNewRush,
    type: 'SUV',
    capacity: '6 People',
    price: 78,
    gasoline: '75L',
    gear: 'Automatic',
  },
  {
    id: 45,
    name: 'CR-V 7',
    img: crv1,
    type: 'SUV',
    capacity: '6 People',
    price: 86,
    gasoline: '85L',
    gear: 'Manual',
  },
  {
    id: 46,
    name: 'All New Terios 7',
    img: allNewTerios,
    type: 'SUV',
    capacity: '6 People',
    price: 80,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 47,
    name: 'MGZX Exclusive 7',
    img: mgzxExclusive,
    type: 'Hatchback',
    capacity: '4 People',
    price: 82,
    gasoline: '70L',
    gear: 'Manual',
  },
  {
    id: 48,
    name: 'New MGZS 12',
    img: newMgzs,
    type: 'SUV',
    capacity: '6 People',
    price: 86,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 49,
    name: 'MGZX Excite 7',
    img: mgzxExcite,
    type: 'Hatchback',
    capacity: '4 People',
    price: 80,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 50,
    name: 'New MGZS 13',
    img: newMgzs2,
    type: 'SUV',
    capacity: '6 People',
    price: 86,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 51,
    name: 'All New Rush 8',
    img: allNewRush,
    type: 'SUV',
    capacity: '6 People',
    price: 79,
    gasoline: '75L',
    gear: 'Automatic',
  },
  {
    id: 52,
    name: 'CR-V 8',
    img: crv1,
    type: 'SUV',
    capacity: '6 People',
    price: 87,
    gasoline: '85L',
    gear: 'Manual',
  },
  {
    id: 53,
    name: 'All New Terios 8',
    img: allNewTerios,
    type: 'SUV',
    capacity: '6 People',
    price: 81,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 54,
    name: 'MGZX Exclusive 8',
    img: mgzxExclusive,
    type: 'Hatchback',
    capacity: '4 People',
    price: 83,
    gasoline: '70L',
    gear: 'Manual',
  },
  {
    id: 55,
    name: 'New MGZS 14',
    img: newMgzs,
    type: 'SUV',
    capacity: '6 People',
    price: 87,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 56,
    name: 'MGZX Excite 8',
    img: mgzxExcite,
    type: 'Hatchback',
    capacity: '4 People',
    price: 81,
    gasoline: '90L',
    gear: 'Manual',
  },
  {
    id: 57,
    name: 'New MGZS 15',
    img: newMgzs2,
    type: 'SUV',
    capacity: '6 People',
    price: 87,
    gasoline: '80L',
    gear: 'Manual',
  },
  {
    id: 58,
    name: 'All New Rush 9',
    img: allNewRush,
    type: 'SUV',
    capacity: '6 People',
    price: 80,
    gasoline: '75L',
    gear: 'Automatic',
  },
];

export const turkishCities: string[] = [
  'Adana',
  'Adıyaman',
  'Afyonkarahisar',
  'Ağrı',
  'Aksaray',
  'Amasya',
  'Ankara',
  'Antalya',
  'Artvin',
  'Aydın',
  'Balıkesir',
  'Bartın',
  'Batman',
  'Bayburt',
  'Bilecik',
  'Bingöl',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Çanakkale',
  'Çankırı',
  'Çorum',
  'Denizli',
  'Diyarbakır',
  'Düzce',
  'Edirne',
  'Elazığ',
  'Erzincan',
  'Erzurum',
  'Eskişehir',
  'Gaziantep',
  'Giresun',
  'Gümüşhane',
  'Hakkari',
  'Hatay',
  'Iğdır',
  'Isparta',
  'İstanbul',
  'İzmir',
  'Kahramanmaraş',
  'Karabük',
  'Karaman',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kırıkkale',
  'Kırklareli',
  'Kırşehir',
  'Kocaeli',
  'Konya',
  'Kütahya',
  'Malatya',
  'Manisa',
  'Mardin',
  'Mersin',
  'Muğla',
  'Muş',
  'Nevşehir',
  'Niğde',
  'Ordu',
  'Osmaniye',
  'Rize',
  'Sakarya',
  'Samsun',
  'Siirt',
  'Sinop',
  'Sivas',
  'Şanlıurfa',
  'Şırnak',
  'Tekirdağ',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Uşak',
  'Van',
  'Yalova',
  'Yozgat',
  'Zonguldak',
];

export const timeSlots: string[] = [
  '09:00',
  '09:30',
  '10:00',
  '10:30',
  '11:00',
  '11:30',
  '12:00',
  '12:30',
  '13:00',
  '13:30',
  '14:00',
  '14:30',
  '15:00',
  '15:30',
  '16:00',
  '16:30',
  '17:00',
  '17:30',
  '18:00',
  '18:30',
  '19:00',
  '19:30',
  '20:00',
  '20:30',
  '21:00',
  '21:30',
  '22:00',
  '22:30',
  '23:00',
  '23:30',
];
